Update src/languages/d.js
I found a problem running mocha. It was giving me the following error:
Error: global leaks detected: integer_re, float_re

I found out that it was a syntax problem that left integer_re and float_re without a "var" declaration, so they are defined in the global scope wich is a potential problem if you use the same name for other global variable.